backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "content/home.md"
        editor:
          preview: false
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: /blog/{{slug}}
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'thumbnail', widget: 'image' }
      - {
        label: 'Artist',
        name: 'artist',
        widget: 'relation',
        multiple: false,
        required: false,
        collection: 'artists',
        search_fields: ['artist'],
        value_field: 'artist',
        display_fields: ['{{artist}}'],
        }
      - {
        label: 'Albums',
        name: 'albums',
        widget: 'relation',
        collection: 'albums',
        required: false,
        search_fields: ['artist', 'title'],
        value_field: '{{slug}}',
        multiple: false,
        }
      - {
        label: 'Photos',
        name: 'photos',
        widget: 'relation',
        collection: 'photos',
        required: false,
        search_fields: ['artist', 'title'],
        value_field: '{{slug}}',
        multiple: false,
        }
      - {
        label: 'Spotify',
        name: 'spotifyId',
        widget: 'string',
        hint: 'Insert the last ID (XXXXXX) after the embed url code https://open.spotify.com/embed/artist/XXXXX',
        required: false,
        }
      - {
        label: 'Youtube',
        name: 'youtubeId',
        widget: 'string',
        hint: 'Insert the last ID (XXXXX) after the embed url code https://www.youtube.com/embed/XXXXX',
        required: false,
        }
  - name: 'albums'
    label: 'Albums'
    folder: 'content/albums'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    preview_path: /albums/{{slug}}
    editor:
      preview: false
    fields:
      - {
          label: 'Artist',
          name: 'artist',
          widget: 'relation',
          collection: 'artists',
          search_fields: ['artist'],
          value_field: 'artist',
          display_fields: ['{{artist}}'],
        }
      - {
          label: "Genres",
          name: "genres",
          widget: "relation",
          collection: "settings",
          file: "content/settings/genres.md",
          search_fields: ["genres.genre"],
          display_fields: ['{{genres.genre}}'],
          value_field: "genres.genre"
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Record label', name: 'recordLabel', widget: 'string' }
      - { label: 'Lineup', name: 'lineup', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'thumbnail', widget: 'image' }
      - {
        label: 'Spotify',
        name: 'spotifyId',
        widget: 'string',
        hint: 'Insert the last ID (XXXXXX) after the embed url code https://open.spotify.com/embed/album/XXXXX',
        required: false,
        }
      - {
          label: 'Youtube',
          name: 'youtubeId',
          widget: 'string',
          hint: 'Insert the last ID (XXXXX) after the embed url code https://www.youtube.com/embed/XXXXX',
          required: false,
        }
  - name: 'artists'
    label: 'Artists'
    folder: 'content/artists'
    format: 'frontmatter'
    create: true
    slug: '{{artist}}'
    preview_path: /artists/{{slug}}
    editor:
      preview: false
    fields:
      - { label: 'Artist', name: 'artist', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Biography', name: 'biography', widget: 'markdown' }
      - { label: 'Thubmnail', name: 'thumbnail', widget: 'image' }
      - { label: 'HeaderImage', name: 'headerImage', widget: 'image' }
      - {
          label: 'Spotify',
          name: 'spotifyId',
          widget: 'string',
          hint: 'Insert the last ID (XXXXXX) after the embed url code https://open.spotify.com/embed/artist/XXXXX',
          required: false,
        }
      - {
          label: 'Youtube',
          name: 'youtubeId',
          widget: 'string',
          hint: 'Insert the last ID (XXXXX) after the embed url code https://www.youtube.com/embed/XXXXX',
          required: false,
        }
  - name: 'photos'
    label: 'Photos'
    folder: 'content/photos'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    preview_path: /photos/{{slug}}
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
        label: 'Artist',
        name: 'artist',
        widget: 'relation',
        multiple: true,
        collection: 'artists',
        search_fields: ['artist'],
        value_field: 'artist',
        display_fields: ['{{artist}}'],
      }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - { label: 'Thubmnail', name: 'thumbnail', widget: 'image' }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        summary: '{{fields.image}}'
        fields:
          - {label: 'Image', name: 'image', widget: 'image' }
          - {label: "Caption", name: "caption", widget: "string", required: false}
  - label: "Settings"
    name: "settings"
    files:
      - label: "Genres"
        name: "genreSetting"
        file: "content/settings/genres.md"
        editor:
          preview: false
        fields:
          - widget: "list"
            name: "genres"
            summary: '{{fields.genre}}'
            field: {label: "Genre", name: "genre", widget: "string"}
