backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: /{{slug}}
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Albums', name: 'albums', widget: 'relation', collection: "albums", search_fields: ['artist', 'title'], value_field: '{{slug}}', multiple: true}
  - name: 'albums'
    label: 'Albums'
    folder: 'content/albums'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    preview_path: /{{slug}}
    editor:
      preview: true
    fields:
      - { label: 'Artist', name: 'artist', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'thumbnail', widget: 'image' }
